
### 1. Analysis of Pasilla Dataset - DESeq2, DESeq, edgeR, limma-voom

~~~~~~~~
library("pasilla")
datafile <- system.file("extdata", "pasilla_gene_counts.tsv", package="pasilla", mustWork=TRUE)
count_table <- read.csv(datafile,sep="\t",row.names="gene_id")
expt <- colnames(count_table)
condition=c("untreated","untreated","untreated","untreated","treated","treated","treated")
design_table=data.frame(expt,condition)
#
############
# DESeq2
############
results_DE2=rna_diff_expr(count_table, design_table, method="DESeq2")
write.csv(as.data.frame(results_DE2), file="DE2.csv")
#
############
# DESeq
############
results_DE=rna_diff_expr(count_table, design_table, method="DESeq")
write.csv(as.data.frame(results_DE), file="DE.csv")
#
############
# edgeR
############
results_edgeR=rna_diff_expr(count_table, design_table, method="edgeR")
write.csv(as.data.frame(results_edgeR), file="edgeR.csv")
#
############
# limma-voom
############
results_limma=rna_diff_expr(count_table, design_table, method="limma-voom")
write.csv(as.data.frame(results_limma), file="limma.csv")
#
~~~~~~~~


as.data.frame(results_DE2) %>% tibble::rownames_to_column() %>% dplyr::filter(pvalue<1e-40)

as.data.frame(results_DE) %>% dplyr::filter(pval<1e-40)

as.data.frame(results_edgeR) %>% tibble::rownames_to_column() %>% dplyr::filter(PValue<1e-40)

as.data.frame(results_limma) %>% tibble::rownames_to_column() %>% head
